//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Zbu.ModelsBuilder v2.1.5.54
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Zbu.ModelsBuilder;
using Zbu.ModelsBuilder.Umbraco;

namespace Umbraco.Extensions.Models
{
    using Our.Umbraco.Vorto.Extensions;

    public partial class UmbNewsItem
    {
        ///<summary>
        ///News
        ///</summary>
        [ImplementPropertyType("news")]
        public Newsdetached News
        {
            get
            {
                var news = this.GetVortoValue<IPublishedContent>("news");

                return news == null ? null : new Newsdetached(news);
            }
        }
    }
}
